
package sm.gcl.iu;

import java.awt.image.BufferedImage;

/**
 * Clase padre usada para la gestión de ventanas internas.
 * Hereda de la clase JInternalFrame
 * @author Germán Castilla López
 */
public class VentanaInternaSM extends javax.swing.JInternalFrame {
    
    /**
     * Constructor de la superclase ventana interna.
     */
    public VentanaInternaSM() {
        initComponents();
    }
    
    /**
     * Método usado para obtener la imagen del vídeo o cámara
     * @return La imagen que devuelva la clase hijo
     */
    public BufferedImage getImage(){
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
