
package sm.gcl.iu;


/**
 * Clase creada para la gestión de ventanas internas a las que se le puede
 * aplicar un lienzo de la clase Lienzo2D.
 * Hereda de la clase VentanaInternaSM
 * @author Germán Castilla López
 */
public class VentanaInternaImagen extends VentanaInternaSM {

    /**
     * Constructor de la clase sin parámetros
     */
    public VentanaInternaImagen() {
        super();
        initComponents();
    }

    /**
     * Método para comprobar el lienzo que tiene asignado la ventana interna
     * @return Objeto de la clase Lienzo2D que tiene asignado la ventana interna
     */
    public Lienzo2D getLienzo2D() {
        return lienzo2D;
    }

    /**
     * Método para indicar el lienzo que debe tener asignado la ventana interna
     * @param lienzo2D Objeto de la clase Lienzo2D que debe tener asignado asignado la ventana interna
     */
    public void setLienzo2D(Lienzo2D lienzo2D) {
        this.lienzo2D = lienzo2D;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2D = new sm.gcl.iu.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(160, 140));

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2D);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.gcl.iu.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables
}
